### PR TITLE
Fix mesh dr example - Sync html and rst

### PR DESCRIPTION
**Pull request by rjodon**
I wanted to run Mesh DR example, It looked like the .html code for Mesh DR example was out-of-date. 
 The related .rst file is OK though.

### CODE REVIEW

**Comment by rjodon** [comment]
@gonzalocasas @brgcode 
I don't know GitHub pages API but wouldn't be simpler  and safer if the repo only contained .rst and .html would be autogenerated on the server side?

**Comment by brgcode** [comment]
yes the current setup is a bit messy but i just wanted to get it started and have an independent place to work on code examples. all suggestions to improve the situation are more than welcome...

**Comment by rjodon** [comment]
@brgcode I will have a look later this week then.

**Comment by brgcode** [comment]
will close this as no longer relevant...

**Comment by rjodon** [comment]
Sure !

**Pull request closed without merging**
