### PR TITLE
adding example volumetric-modeling-of-logo

### PR DESCRIPTION
**Pull request by brgcode**

### CODE REVIEW

**Comment by brgcode** [comment]
first attempt at using PR with submodules to add examples. through a workflow this should now be checked and rendered into the docs folder and pushed to the gh-pages branch if successful...

**Review by gonzalocasas — APPROVED** [review]
LGTM!

**Comment by brgcode** [comment]
@Licini could you set up a workflow that tests the PR (run example script in environment specified in environment file) and another one that re-generates the docs and pushes to gh-pages once the PR is merged

**Comment by brgcode** [comment]
i guess we will have to try this procedure a few times as i add examples to get it right...

**Pull request closed without merging**
